import type { ModelProfile } from "./types";
export const genericProfile: ModelProfile = {
  normalize: true,
  screenNames: ["Minitel_Screen", "Screen", "CRT"],
  screenFallback: { position: [0, 1.28, 0.75], size: [1.91, 1.56] },
  anchors: {
    top: { position: [0, 2.4, 0] },
    left: { position: [-1.24, 1.2, 0] },
    right: { position: [1.24, 1.2, 0] },
    rear: { position: [0, 1.1, -1] },
  },
  keys: {},
};
export const suppliedProfile: ModelProfile = {
  ...genericProfile,
  normalize: false,
  // Bounds centre of Minitel_Screen in public/models/minitel.glb.
  screenCenter: [0, 1.282, 0.743],
  // Minitel_Screen is two flat triangles : bulge it like the CRT glass.
  screenBulge: 0.16,
  keys: {
    Object_51: "1",
    Object_52: "2",
    Object_53: "3",
    Object_48: "4",
    Object_49: "5",
    Object_50: "6",
    Object_54: "7",
    Object_56: "8",
    Object_55: "9",
    Object_42: "0",
    Object_57: "*",
    Object_58: "#",
    Object_46: "ConnexionFin",
    Object_37: "Repetition",
    Object_38: "Annulation",
    Object_39: "Retour",
    Object_43: "Sommaire",
    Object_40: "Correction",
    Object_41: "Suite",
    Object_45: "Guide",
    Object_44: "Envoi",
    Object_20: "A",
    Object_69: "Z",
    Object_70: "E",
    Object_68: "R",
    Object_11: "T",
    Object_13: "Y",
    Object_14: "U",
    Object_12: "I",
    Object_10: "O",
    Object_21: "P",
    Object_23: "Q",
    Object_66: "S",
    Object_67: "D",
    Object_65: "F",
    Object_60: "G",
    Object_61: "H",
    Object_62: "J",
    Object_64: "K",
    Object_63: "L",
    Object_24: "M",
    Object_22: "W",
    Object_17: "X",
    Object_18: "C",
    Object_16: "V",
    Object_15: "B",
    Object_59: "N",
    Object_25: " ",
  },
};
// Web copy of "1950's Retro Television" (tools/prepare_television.py):
// 2.4 units high, about 3.55 wide, screen already named Minitel_Screen.
export const televisionProfile: ModelProfile = {
  ...genericProfile,
  normalize: false,
  screenFallback: { position: [0, 1.73, 0.5], size: [1.34, 1.12] },
  // Bounds centre of Minitel_Screen in public/models/television-1950.glb.
  screenCenter: [0.014, 1.732, 0.46],
  anchors: {
    top: { position: [0, 2.4, 0] },
    left: { position: [-1.78, 1.2, 0] },
    right: { position: [1.78, 1.2, 0] },
    rear: { position: [0, 1.2, -0.5] },
  },
};
